### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by rrayst** [membrane/monitor#3]
0    [main] INFO  com.predic8.membrane.core.CoreActivator  - Eclipse framework found config file: file:\C:\Users\Teilnehmer\Desktop\membrane-monitor-win64-3.2.2\configuration\monitor-beans.xml
0    [main] INFO  com.predic8.membrane.core.CoreActivator  - Reading router configuration from file:\C:\Users\Teilnehmer\Desktop\membrane-monitor-win64-3.2.2\configuration\monitor-beans.xml
0    [main] INFO  com.predic8.membrane.core.CoreActivator  - Project root: file:\C:\Users\Teilnehmer\Desktop\membrane-monitor-win64-3.2.2
31   [main] INFO  org.springframework.context.support.FileSystemXmlApplicationContext  - Refreshing org.springframework.context.support.FileSystemXmlApplicationContext@626469f4: startup date [Fri Nov 29 09:14:25 CET 2013]; root of context hierarchy
62   [main] INFO  org.springframework.beans.factory.xml.XmlBeanDefinitionReader  - Loading XML bean definitions from URL [file:/C:/Users/Teilnehmer/Desktop/membrane-monitor-win64-3.2.2/configuration/monitor-beans.xml]
171  [main] INFO  org.springframework.beans.factory.support.DefaultListableBeanFactory  - Pre-instantiating singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@7259f725: defining beans [router,exchangeStore,transport,JSONBeautifier]; root of factory hierarchy
312  [main] INFO  com.predic8.membrane.core.CoreActivator  - Router instance: com.predic8.membrane.core.Router@4419bacb
312  [pool-1-thread-1] WARN  com.predic8.membrane.core.CoreActivator  - no configuration loaded
java.io.FileNotFoundException: C:\Users\Teilnehmer.membrane.xml (Das System kann die angegebene Datei nicht finden)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at com.predic8.membrane.core.util.ResourceResolver.resolve(ResourceResolver.java:23)
    at com.predic8.membrane.core.util.ResourceResolver.resolve(ResourceResolver.java:12)
    at com.predic8.membrane.core.io.ConfigurationFileStore.read(ConfigurationFileStore.java:40)
    at com.predic8.membrane.core.ConfigurationManager.loadConfiguration(ConfigurationManager.java:45)
    at com.predic8.membrane.core.CoreActivator$1.run(CoreActivator.java:78)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:724)
7323130 [RouterThread /0:0:0:0:0:0:0:1:49653] INFO  com.predic8.membrane.core.transport.http.HttpClient  - Connection to http://localhost:8080/Auktionshaus/webresources/auktionen/2/bildwas aborted externally. Maybe by the server or the OS Membrane is running on.
7582844 [main] WARN  com.predic8.membrane.core.logger.MembraneLogListener  - Problems occurred when invoking code from plug-in: "org.eclipse.jface".

**Comment by symle** [comment]
is it occur in "windows" right
